function createfigure2(zdata1, figure2)
%CREATEFIGURE(zdata1)
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 03-Apr-2019 17:40:51

% Create figure
figure1 = figure2;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
surf(zdata1,'Parent',axes1);

view(axes1,[-37.5 30]);
grid(axes1,'on');
